from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "assets"
SVG_PATH = ASSET_DIR / "toki-downloader.svg"
PNG_PATH = ASSET_DIR / "toki-downloader.png"
ICO_PATH = ASSET_DIR / "toki-downloader.ico"
BACKGROUND = "#101c30"
OUTER_STROKE = "#4bd5f7"
INNER_STROKE = "#203a59"
ARROW_COLOR = "#45cbea"
BADGE_COLOR = "#ff5d8f"
OUTER_BOX = (8, 8, 248, 248)
INNER_BOX = (21, 21, 235, 235)
ARROW_POINTS = (
    (63, 61), (193, 61), (193, 89), (143, 89), (143, 150),
    (178, 115), (199, 136), (128, 207), (57, 136), (78, 115),
    (113, 150), (113, 89), (63, 89),
)
BADGE_BOX = (175, 34, 221, 80)
CHECK_POINTS = ((188, 57), (195, 64), (209, 47))


def _svg_points(values: tuple[tuple[int, int], ...]) -> str:
    return " ".join(f"{x},{y}" for x, y in values)


SVG_CONTENT = f"""<!-- Generated by scripts/generate_app_icons.py; do not edit directly. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">
  <rect x="8" y="8" width="240" height="240" rx="52" fill="{BACKGROUND}" stroke="{OUTER_STROKE}" stroke-width="8"/>
  <rect x="21" y="21" width="214" height="214" rx="39" fill="none" stroke="{INNER_STROKE}" stroke-width="4"/>
  <polygon points="{_svg_points(ARROW_POINTS)}" fill="{ARROW_COLOR}"/>
  <circle cx="198" cy="57" r="23" fill="{BADGE_COLOR}"/>
  <path d="M188 57 L195 64 L209 47" fill="none" stroke="#fff" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
"""


def build_icon(size: int = 1024) -> Image.Image:
    from PIL import Image, ImageDraw

    scale = size / 256

    def points(values: list[tuple[int, int]]) -> list[tuple[int, int]]:
        return [(round(x * scale), round(y * scale)) for x, y in values]

    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle(
        tuple(value * scale for value in OUTER_BOX),
        radius=52 * scale,
        fill=BACKGROUND,
        outline=OUTER_STROKE,
        width=max(1, round(8 * scale)),
    )
    draw.rounded_rectangle(
        tuple(value * scale for value in INNER_BOX),
        radius=39 * scale,
        outline=INNER_STROKE,
        width=max(1, round(4 * scale)),
    )
    draw.polygon(
        points(list(ARROW_POINTS)),
        fill=ARROW_COLOR,
    )
    draw.ellipse(
        tuple(value * scale for value in BADGE_BOX),
        fill=BADGE_COLOR,
    )
    draw.line(
        points(list(CHECK_POINTS)),
        fill="white",
        width=max(1, round(7 * scale)),
        joint="curve",
    )
    return image


def main() -> None:
    from PIL import Image

    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    SVG_PATH.write_text(SVG_CONTENT, encoding="utf-8", newline="\n")
    source = build_icon()
    png = source.resize((256, 256), Image.Resampling.LANCZOS)
    png.save(PNG_PATH, format="PNG", optimize=True)
    source.save(
        ICO_PATH,
        format="ICO",
        sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
    )
    print(SVG_PATH)
    print(PNG_PATH)
    print(ICO_PATH)


if __name__ == "__main__":
    main()
